### ISSUE TITLE
Does not seem to work with rmagick 4.0.0

### ISSUE THREAD

**Issue by RandieM** [jakesgordon/sprite-factory#54]
Hello there,

In a Rails project, when running the resprite rake task, I get the following error:
```
rake aborted!
NoMethodError: undefined method 'opacity=' for   4013x148 DirectClass 16-bit:Magick::Image
/home/user/.gem/ruby/ruby/2.5.0/gems/sprite-factory-1.7.1/lib/sprite_factory/library/rmagick.rb:23:in 'create'
/home/user/.gem/ruby/ruby/2.5.0/gems/sprite-factory-1.7.1/lib/sprite_factory/runner.rb:243:in 'create_sprite'
/home/user/.gem/ruby/ruby/2.5.0/gems/sprite-factory-1.7.1/lib/sprite_factory/runner.rb:65:in 'run!'
/home/user/.gem/ruby/ruby/2.5.0/gems/sprite-factory-1.7.1/lib/sprite_factory.rb:14:in 'run!'
/home/user/path/to/project/lib/tasks/assets.rake:7:in 'block (2 levels) in <top (required)>'
/home/user/.gem/ruby/ruby/2.5.0/gems/rake-13.0.1/exe/rake:27:in '<top (required)>'
/home/user/.gem/ruby/gems/bundler-1.17.2/lib/bundler/cli/exec.rb:74:in 'load'
/home/user/.gem/ruby/gems/bundler-1.17.2/lib/bundler/cli/exec.rb:74:in 'kernel_load'
/home/user/.gem/ruby/gems/bundler-1.17.2/lib/bundler/cli/exec.rb:28:in 'run'
/home/user/.gem/ruby/gems/bundler-1.17.2/lib/bundler/cli.rb:463:in 'exec'
/home/user/.gem/ruby/gems/bundler-1.17.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in 'run'
/home/user/.gem/ruby/gems/bundler-1.17.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in 'invoke_command'
/home/user/.gem/ruby/gems/bundler-1.17.2/lib/bundler/vendor/thor/lib/thor.rb:387:in 'dispatch'
/home/user/.gem/ruby/gems/bundler-1.17.2/lib/bundler/cli.rb:27:in 'dispatch'
/home/user/.gem/ruby/gems/bundler-1.17.2/lib/bundler/vendor/thor/lib/thor/base.rb:466:in 'start'
/home/user/.gem/ruby/gems/bundler-1.17.2/lib/bundler/cli.rb:18:in 'start'
/home/user/.gem/ruby/gems/bundler-1.17.2/exe/bundle:30:in 'block in <top (required)>'
/home/user/.gem/ruby/gems/bundler-1.17.2/lib/bundler/friendly_errors.rb:124:in 'with_friendly_errors'
/home/user/.gem/ruby/gems/bundler-1.17.2/exe/bundle:22:in '<top (required)>'
/home/user/bin/bundle:23:in 'load'
/home/user/bin/bundle:23:in '<main>'
Tasks: TOP => assets:resprite

It happens with rmagick 4.0.0, but not with earlier versions of the gem.

Let me know if you need more information.

Many thanks!

**Comment by RandieM** [comment]
Relevant pull request: #55
